[package]
name = "simple-todo"
description = "Simple TODO example api"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Netwo <oss@netwo.com>"]

[dependencies]
actix-web = "4"
apistos = { path = "../../apistos", features = ["extras", "qs_query"] }
schemars = { git = "https://github.com/rlebran-netwo/schemars", branch = "fix-multiple-flatten", features = ["chrono", "uuid1", "url", "rust_decimal"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4", features = ["serde", "v4"] }

[workspace]
