[package]
name = "apistos-gen-test"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
actix-multipart = { workspace = true }
actix-web = { workspace = true }
assert-json-diff = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
futures-core = { workspace = true }
apistos = { path = "../apistos", features = ["multipart"] }
apistos-core = { path = "../apistos-core" }
apistos-gen = { path = "../apistos-gen" }
schemars = { workspace = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { workspace = true }
