[workspace]
resolver = "2"
members = [
    "netwopenapi",
    "netwopenapi-gen"
]

[workspace.package]
authors = ["Netwo <tech-team@netwo.com>"]
edition = "2021"
repository = "https://gitlab.dev-factory.netwo.dev/saas/netwopenapi"
publish = false
rust-version = "1.71"

[workspace.dependencies]
actix-service = "2"
actix-web = "4"
convert_case = "0.6"
darling = "0.20"
once_cell = "1"
pin-project = "1"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
regex = "1"
serde = "1"
serde_json = "1"
syn = "2.0"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-rapidoc = { version = "0", features = ["actix-web"] }
utoipa-redoc = { version = "0", features = ["actix-web"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }

actix-multipart = "0.6"
actix-web-garde = { path = "../actix-web-garde" }
chrono = "0.4"
garde = "0.14"
serde_qs = "0.12"
rust_decimal = "1"
uuid = "1"
