[workspace]
members = [
    "netwopenapi",
    "netwopenapi-gen"
]

[workspace.package]
authors = ["Netwo <tech-team@netwo.com>"]
edition = "2021"
repository = "https://gitlab.netwo.io/netwo1/netwopenapi"
publish = false
rust-version = "1.71"

[workspace.dependencies]
actix-service = "2"
actix-web = "4"
once_cell = "1"
pin-project = "1"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
regex = "1"
serde = "1"
serde_json = "1"
syn = "2.0"
utoipa = { version = "3", features = ["actix_extras"] }

bytes = { version = "1" }
uuid = { version = "1" }
