[package]
name = "netwopenapi-core"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
netwopenapi-models = { path = "../netwopenapi-models" }
