[package]
name = "petstore"
description = "Simple petstore example api with utoipa and Swagger"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
    "Example <example@example.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10.0"
future-utils = "0.12"
log = "0.4"
futures = "0.3"
utoipa = { version = "3", features = ["actix_extras", "debug"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
uuid = { version = "1", features = ["serde", "v4"] }

netwopenapi = { path = "../../netwopenapi", features = ["extras"] }

[workspace]
