[package]
name = "petstore"
description = "Simple petstore example api with utoipa and Swagger"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
    "Example <example@example.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
env_logger = "0.10.0"
future-utils = "0.12"
futures = "0.3"
log = "0.4"
num-traits = "0.2"
rust_decimal = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = { version = "0.12", features = ["actix4"] }
uuid = { version = "1", features = ["serde", "v4"] }
utoipa = { git = "https://github.com/juhaku/utoipa.git", features = ["actix_extras", "debug"] }
url = { version = "2", features = ["serde"] }

netwopenapi = { path = "../../netwopenapi", features = ["extras", "swagger-ui", "rapidoc", "redoc", "qs_query"] }

[workspace]
