[package]
name = "netwopenapi"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = { workspace = true }
actix-web = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
utoipa-rapidoc = { workspace = true, optional = true }
utoipa-redoc = { workspace = true, optional = true }
utoipa-swagger-ui = { workspace = true, optional = true }

netwopenapi-gen = { path = "../netwopenapi-gen" }

chrono = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
serde_qs = { workspace = true, features = ["actix4"], optional = true }

[features]
# query related features
query = []
qs_query = ["serde_qs"]

# extra types related features
chrono = ["dep:chrono", "utoipa/chrono"]
rust_decimal = ["dep:rust_decimal", "utoipa/decimal"]
uuid = ["dep:uuid", "utoipa/uuid"]
extras = ["chrono", "uuid", "rust_decimal"]

# UI related features
rapidoc = ["utoipa-rapidoc"]
redoc = ["utoipa-redoc"]
swagger-ui = ["utoipa-swagger-ui"]

default = ["query"]
