[package]
name = "netwopenapi"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = { workspace = true }
actix-web = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }

netwopenapi-gen = { path = "../netwopenapi-gen" }

bytes = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[features]
bytes = ["dep:bytes"]
uuid = ["dep:uuid", "utoipa/uuid"]
extras = ["bytes", "uuid"]
