name: apistos deny

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**Cargo.toml"
      - "deny.toml"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**Cargo.toml"
      - "deny.toml"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check licenses sources advisories
