name: netwopenapi deny

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**Cargo.toml"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**Cargo.toml"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check deny
        run: |
          cargo install cargo-deny --force
          cargo deny check licenses sources advisories
